[package]
name = "alternator"
version = "0.3.0"
authors = ["rumblefrog <contact@rumblefrog.me>"]
edition = "2021"
description = "SourcePawn include parser producing documentation strands"

[dependencies]
schema = { path = "../libschema" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spdcp = { git = "https://github.com/rumblefrog/sp-dcp", rev = "584897c42a6e011d3c92e3e0db2f78f24de2f5f8", features = ["serde"] }
thiserror = "1"
tree-sitter = "0.26"
tree-sitter-sourcepawn = "=0.8.0"
