#!/usr/bin/env bash
# Vendors upstream SourcePawn sources used as parser regression tests.
#
# Usage: libalternator/tests/update-corpus.sh
#
# Each entry is pinned to a commit. After bumping a commit, re-run this script
# and then `ALTERNATOR_BLESS=1 cargo test -p alternator --test corpus` to
# update the expected output, and review the diff.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
corpus="$here/corpus"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# suite|repository|commit|license|patterns...
entries=(
  "sourcemod|alliedmodders/sourcemod|6eb5f8fa381100ed7cac1ab62a4ece11795a5d92|GPL-3.0 (with SourceMod exception)|plugins/include/*.inc plugins/*.sp plugins/*/*.sp"
  "autoexecconfig|Impact123/AutoExecConfig|ccd723616a6fa09faa894337d58a58258aaa389d|GPL-3.0|autoexecconfig.inc"
  "bytebuffer|rumblefrog/SM-ByteBuffer-Inc|57d580ab2183c5f7da85120bdd90056dc29ad118|GPL-3.0|*.inc"
  "includelibrary|JoinedSenses/SourceMod-IncludeLibrary|9d4e4263b77aa0c4fcdadd498c1420c64b3c1c10|LGPL-3.0|include/ccc.inc include/cccm.inc include/chat-processor.inc include/cURL.inc include/cURL_header.inc include/morecolors.inc include/steamtools.inc include/steamworks.inc include/tf2attributes.inc include/tf2items.inc include/tf2items_stocks.inc"
  "json|clugg/sm-json|fd63b4458cea4ba61d1bb84b5491f1b988b61fdb|GPL-3.0|addons/sourcemod/scripting/include/json.inc addons/sourcemod/scripting/include/json/*.inc addons/sourcemod/scripting/include/json/helpers/*.inc addons/sourcemod/scripting/*.sp"
  "multicolors|Bara/Multi-Colors|d2f2dc9126255571c0fc4499d5729cacb57265ca|GPL-3.0|addons/sourcemod/scripting/include/multicolors.inc addons/sourcemod/scripting/include/multicolors/*.inc"
  "ripext|ErikMinekus/sm-ripext|a607852767015fe358537092eba9f3611fb20b3f|GPL-3.0|pawn/scripting/include/ripext.inc pawn/scripting/include/ripext/*.inc pawn/scripting/*.sp"
  "sbpp|sbpp/sourcebans-pp|0bf2a772e00dbd7f182a7f524bb154063acc3c5e|GPL-3.0|game/addons/sourcemod/scripting/include/*.inc game/addons/sourcemod/scripting/*.sp"
  "socket|JoinedSenses/sm-ext-socket|f699399524dd0c0f4710400b38dda0f0f9e7d5d8|GPL-2.0|scripting/include/socket.inc"
  "source-chat-relay|rumblefrog/source-chat-relay|7077e906c891ce2e40d7bc1bac4ef62280937da2|GPL-3.0|client/include/*.inc client/*.sp"
  "ttt|TroubleInTerroristTown/Public|aa9699cbc403023a4947e6d60a263cb3f95919b7|GPL-3.0|addons/sourcemod/scripting/include/ttt.inc addons/sourcemod/scripting/include/ttt_*.inc"
)

rm -rf "$corpus"
mkdir -p "$corpus"

{
  echo "# Parser regression corpus"
  echo
  echo "Unmodified upstream SourcePawn sources used as regression tests for the"
  echo "parser. Generated by \`../update-corpus.sh\`; each file keeps its original"
  echo "license, listed below."
  echo
  echo "| Suite | Repository | Commit | License |"
  echo "| --- | --- | --- | --- |"
} > "$work/SOURCES.md"

for entry in "${entries[@]}"; do
  IFS='|' read -r suite repo commit license patterns <<< "$entry"
  echo "Fetching $repo@$commit"

  dir="$work/$suite"
  git init -q "$dir"
  git -C "$dir" fetch -q --depth 1 "https://github.com/$repo.git" "$commit"
  git -C "$dir" checkout -q FETCH_HEAD

  (
    cd "$dir"
    shopt -s nullglob
    for pattern in $patterns; do
      for file in $pattern; do
        mkdir -p "$corpus/$suite/$(dirname "$file")"
        cp "$file" "$corpus/$suite/$file"
      done
    done
  )

  echo "| \`$suite\` | [$repo](https://github.com/$repo) | \`${commit:0:10}\` | $license |" >> "$work/SOURCES.md"
done

cp "$work/SOURCES.md" "$corpus/SOURCES.md"
echo "Vendored $(find "$corpus" -type f ! -name SOURCES.md | wc -l) files"
