[package]
name = "walker"
version = "0.1.0"
authors = ["rumblefrog <contact@rumblefrog.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
thiserror = "1"
