name: Build docgen

on: [push, pull_request]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout generator
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Test parser and schema
        run: cargo test -p alternator -p schema

      - name: Test walker history
        run: cargo test -p walker --test history

  generator:
    name: DocGen

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout generator
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build chumbucket
        run: cargo build --release -p chumbucket

      - name: Upload docgen
        uses: actions/upload-artifact@v4
        with:
          name: docgen-${{ matrix.os }}
          path: |
            target/release/chumbucket
            target/release/chumbucket.exe
          if-no-files-found: error
